export enum StrategyHolderButtonIds {

  OPEN_SWAP_BUTTON_ID,

  OPEN_LOGS_BUTTON_ID,

  OPEN_ANALYTICS_BUTTON_ID,

  CHANGE_GAS_PRICE_BUTTON_ID,

  CHANGE_TOKEN_B_PRICE_BUTTON_ID,

  CHANGE_GROW_PERCENT_BUTTON_ID,

  CHANGE_FALL_PERCENT_BUTTON_ID,

  CHANGE_STOP_LOSS_PERCENT_BUTTON_ID,

  CANCEL_ORDER_BUTTON_ID,

  DELETE_ORDER_BUTTON_ID,

  PLAY_ORDER_BUTTON_ID,

  PAUSE_ORDER_BUTTON_ID,

  FORCE_EXECUTE_ORDER_BUTTON_ID,
}
